remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
author: Pradyuman
github_username: legendary-acp
permalink: /:year/:month/:day/:title/

# Site settings
title: Pradyuman's Blog
description: Exploring technology, one post at a time
url: "https://legendary-acp.github.io"
baseurl: "/papershelf"  # This is crucial for your GitHub Pages project site

# Social links
social:
  github: legendary-acp